from app.intelligence.news.contracts import (
    NEWS_SERVICE_VERSION,
    ConfidenceLabel,
    CorrectionLineage,
    CorrectionStatus,
    EntityMapping,
    EntityType,
    EventProviderMetadata,
    ExpectedDirection,
    EvidenceKind,
    InterpretationClass,
    MappingRelationship,
    MarketReactionAssessment,
    MarketReactionObservation,
    MaterialityAssessment,
    MaterialityContribution,
    MaterialityInputs,
    NewsAvailability,
    NewsContractModel,
    NewsContradiction,
    NewsClusterSourceMember,
    NewsDeepLink,
    NewsEventCluster,
    NewsEventRecord,
    NewsEventStatus,
    NewsEventType,
    NewsEvidenceRecord,
    NewsFreshness,
    NewsFreshnessState,
    NewsIntelligenceResult,
    NewsProviderMode,
    NewsProviderProvenance,
    NewsProcessingMetrics,
    NewsQuery,
    NewsQueryMode,
    NewsServiceStatus,
    NewsSessionPhase,
    ReactionClassification,
    ReactionWindow,
    SourceQuality,
    SourceRegistryRecord,
)
__all__ = [
    "NEWS_SERVICE_VERSION",
    "ConfidenceLabel",
    "CorrectionLineage",
    "CorrectionStatus",
    "EntityMapping",
    "EntityType",
    "EventProviderMetadata",
    "ExpectedDirection",
    "EvidenceKind",
    "InterpretationClass",
    "MappingRelationship",
    "MarketReactionAssessment",
    "MarketReactionObservation",
    "MaterialityAssessment",
    "MaterialityContribution",
    "MaterialityInputs",
    "NewsAvailability",
    "NewsContractModel",
    "NewsContradiction",
    "NewsClusterSourceMember",
    "NewsDeepLink",
    "NewsEventCluster",
    "NewsEventRecord",
    "NewsEventStatus",
    "NewsEventType",
    "NewsEvidenceRecord",
    "NewsFreshness",
    "NewsFreshnessState",
    "NewsIntelligenceResult",
    "NewsProviderMode",
    "NewsProviderProvenance",
    "NewsProcessingMetrics",
    "NewsQuery",
    "NewsQueryMode",
    "NewsServiceStatus",
    "NewsSessionPhase",
    "ReactionClassification",
    "ReactionWindow",
    "SourceQuality",
    "SourceRegistryRecord",
    "NewsIntelligenceService",
    "get_news_intelligence_service",
    "reset_news_intelligence_service",
]


def __getattr__(name: str):
    # Provider contracts import this package before the service layer exists;
    # keep the public service seam lazy to avoid a package initialization cycle.
    if name in {
        "NewsIntelligenceService",
        "get_news_intelligence_service",
        "reset_news_intelligence_service",
    }:
        from app.intelligence.news.service import (
            NewsIntelligenceService,
            get_news_intelligence_service,
            reset_news_intelligence_service,
        )

        return {
            "NewsIntelligenceService": NewsIntelligenceService,
            "get_news_intelligence_service": get_news_intelligence_service,
            "reset_news_intelligence_service": reset_news_intelligence_service,
        }[name]
    raise AttributeError(name)
