from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Literal

ProviderDomain = Literal["none", "quotes", "history", "quotes+history", "intelligence", "ai"]
ValidationTier = Literal["required", "optional", "manual"]


@dataclass(frozen=True)
class EndpointSpec:
    method: str
    path: str
    screen: str
    frontend_api: str
    backend_service: str
    response_model: str
    provider_domain: ProviderDomain = "none"
    required_fields: tuple[str, ...] = ()
    optional_fields: tuple[str, ...] = ()
    allowed_source_states: tuple[str, ...] = ("live", "cached", "stale", "mock", "mixed", "unavailable", "partial", "delayed", "initializing")
    partial_supported: bool = True
    live_required: bool = False
    test_required: bool = True
    tier: ValidationTier = "required"
    timeout_seconds: float = 10.0

    def model_dump(self) -> dict[str, object]:
        return asdict(self)


CORE_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        "GET",
        "/health",
        "System",
        "health",
        "main.health_check",
        "dict",
        required_fields=("status",),
        timeout_seconds=3,
    ),
    EndpointSpec(
        "GET",
        "/system/provider-status",
        "Data Sources",
        "getProviderStatus",
        "providers.selector.get_provider_status",
        "dict",
        required_fields=("configured_quote_provider", "configured_history_provider", "fallback_enabled"),
        provider_domain="quotes+history",
    ),
    EndpointSpec(
        "GET",
        "/market-data/cache/status",
        "Data Sources",
        "getMarketDataCacheStatus",
        "market_data_repository.get_cache_status",
        "dict",
        required_fields=("provider_routing",),
        provider_domain="quotes+history",
    ),
    EndpointSpec(
        "GET",
        "/system/service-cache",
        "Data Usage",
        "getServiceCacheStatus",
        "service_cache.get_service_cache_status",
        "dict",
        required_fields=("items", "hit_count", "miss_count"),
    ),
    EndpointSpec(
        "GET",
        "/system/universe-status",
        "Data Sources",
        "getUniverseStatus",
        "breadth.get_universe_status",
        "dict",
        required_fields=("breadth_universe",),
    ),
    EndpointSpec(
        "GET",
        "/home/dashboard",
        "Home",
        "getHomeDashboard",
        "home_dashboard.build_home_dashboard",
        "HomeDashboardResponse",
        required_fields=("core", "watchlist_summary"),
        optional_fields=("risk_summary",),
        provider_domain="quotes+history",
        timeout_seconds=8,
    ),
    EndpointSpec(
        "GET",
        "/market/core-snapshot",
        "Market Overview",
        "getMarketCoreSnapshot",
        "market_core_snapshot.build_market_core_snapshot",
        "MarketCoreSnapshot",
        required_fields=("indexes", "market_health", "decision_summary", "as_of"),
        optional_fields=("breadth_summary", "top_sector", "top_industry_group"),
        provider_domain="quotes+history",
        timeout_seconds=8,
    ),
    EndpointSpec(
        "GET",
        "/market/indexes",
        "Market Indexes",
        "getMarketIndexes",
        "market_data.get_index_snapshots",
        "IndexesResponse",
        required_fields=("indexes",),
        provider_domain="quotes+history",
        timeout_seconds=10,
    ),
    EndpointSpec(
        "GET",
        "/market/breadth",
        "Market Breadth",
        "getMarketBreadth",
        "breadth.calculate_market_breadth",
        "SectorBreadthResponse",
        required_fields=("market", "sectors"),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/health",
        "Market Health",
        "getMarketHealth",
        "market_health.calculate_market_health",
        "MarketHealthResponse",
        required_fields=("overall_score", "status", "components", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/decision-dashboard",
        "Market Decision",
        "getDecisionDashboard",
        "decision_intelligence.build_decision_dashboard",
        "DecisionDashboardResponse",
        required_fields=("aggressiveness", "playbook", "decision_confidence"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/details/decision",
        "Market Decision",
        "getMarketDecisionDetails",
        "market_detail_aggregates.build_market_decision_details",
        "dict",
        required_fields=("decisionDashboard", "probabilities", "comparison", "riskDashboard"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/details/institutional",
        "Market Institutional",
        "getMarketInstitutionalDetails",
        "market_detail_aggregates.build_market_institutional_details",
        "dict",
        required_fields=("sentiment", "moneyFlow", "institutional", "options", "liquidity"),
        provider_domain="intelligence",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/details/structure",
        "Market Structure",
        "getMarketStructureDetails",
        "market_detail_aggregates.build_market_structure_details",
        "dict",
        required_fields=("breadth", "sectors", "industryGroups", "industryRotation", "leadership"),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/sector-dashboard",
        "Sectors",
        "getSectorDashboard",
        "sector_dashboard.build_sector_dashboard",
        "SectorDashboardResponse",
        required_fields=("sectors", "themes"),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/sectors/summary",
        "Sectors",
        "getSectorsSummary",
        "sectors_summary.build_sectors_summary",
        "SectorsSummaryResponse",
        required_fields=("top_sectors", "top_industry_groups", "rotation_summary"),
        provider_domain="history",
        timeout_seconds=10,
    ),
    EndpointSpec(
        "GET",
        "/market/sectors",
        "Sectors Legacy",
        "getMarketSectors",
        "sectors.build_market_sectors",
        "SectorsResponse",
        required_fields=("leaders", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/industry-groups",
        "Themes Legacy",
        "getIndustryGroups",
        "industry_groups.build_industry_groups",
        "IndustryGroupResponse",
        required_fields=("items",),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/industry-rotation",
        "Themes Rotation",
        "getIndustryRotation",
        "industry_rotation.build_industry_rotation_dashboard",
        "IndustryRotationResponse",
        required_fields=("sectors", "summary"),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/sector-etfs",
        "Sector ETFs",
        "getSectorEtfs",
        "sector_etfs.build_sector_etf_dashboard",
        "SectorEtfResponse",
        required_fields=("items",),
        provider_domain="quotes+history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/watchlist/summary",
        "Watchlist",
        "getWatchlistSummary",
        "watchlist_summary.build_watchlist_summary",
        "WatchlistSummaryResponse",
        required_fields=("items",),
        provider_domain="quotes+history",
        timeout_seconds=8,
    ),
    EndpointSpec(
        "GET",
        "/market/relative-strength",
        "Watchlist Signals",
        "getRelativeStrength",
        "relative_strength.build_relative_strength",
        "RelativeStrengthResponse",
        required_fields=("items", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/stock-ratings",
        "Watchlist Overview",
        "getStockRatings",
        "stock_rating.build_stock_ratings",
        "StockRatingResponse",
        required_fields=("items", "summary"),
        provider_domain="history",
        timeout_seconds=15,
    ),
    EndpointSpec(
        "GET",
        "/market/sentiment",
        "Market Institutional",
        "getMarketSentiment",
        "market_sentiment.build_market_sentiment_dashboard",
        "MarketSentimentResponse",
        required_fields=("score", "status", "summary"),
        provider_domain="intelligence",
    ),
    EndpointSpec(
        "GET",
        "/market/money-flow",
        "Market Institutional",
        "getMoneyFlow",
        "money_flow.build_money_flow_dashboard",
        "MoneyFlowResponse",
        required_fields=("score", "status", "summary"),
        provider_domain="intelligence",
    ),
    EndpointSpec(
        "GET",
        "/market/institutional",
        "Market Institutional",
        "getMarketInstitutional",
        "institutional_dashboard.build_institutional_dashboard",
        "InstitutionalDashboardResponse",
        required_fields=("score", "status", "summary"),
        provider_domain="intelligence",
    ),
    EndpointSpec(
        "GET",
        "/market/options",
        "Market Institutional",
        "getOptionsIntelligence",
        "options_intelligence.build_options_intelligence",
        "OptionsIntelligenceResponse",
        required_fields=("score", "status", "summary"),
        provider_domain="intelligence",
    ),
    EndpointSpec(
        "GET",
        "/market/liquidity",
        "Market Institutional",
        "getLiquidityDashboard",
        "liquidity_dashboard.build_liquidity_dashboard",
        "LiquidityDashboardResponse",
        required_fields=("score", "status", "summary"),
        provider_domain="quotes+history",
    ),
    EndpointSpec(
        "GET",
        "/analysis/market",
        "Copilot Context",
        "market analysis context",
        "analysis.build_market_analysis",
        "MarketAnalysisResponse",
        required_fields=("market_health", "summary_points", "ai_prompt_context"),
        provider_domain="history",
        timeout_seconds=15,
    ),
)


SYMBOL_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        "GET",
        "/market/live/quote/{symbol}",
        "Stock Detail Quote",
        "getLiveQuote",
        "market_data_repository.get_quote",
        "QuoteData",
        required_fields=("symbol", "price", "timestamp", "source"),
        provider_domain="quotes",
        live_required=True,
    ),
    EndpointSpec(
        "GET",
        "/market/live/history/{symbol}?resolution=D&days=260",
        "Stock Detail Chart",
        "getLiveHistory",
        "market_data_repository.get_history",
        "HistoryData",
        required_fields=("symbol", "candles", "source", "as_of"),
        provider_domain="history",
        live_required=True,
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/live/history/{symbol}?resolution=D&days=60",
        "Stock Detail Chart 1M",
        "getLiveHistory",
        "market_data_repository.get_history",
        "HistoryData",
        required_fields=("symbol", "candles", "source", "as_of"),
        provider_domain="history",
        live_required=True,
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/support-resistance/{symbol}",
        "Stock Detail Technical",
        "getSupportResistance",
        "support_resistance.calculate_support_resistance",
        "SupportResistanceResponse",
        required_fields=("symbol", "current_price", "support_zones", "resistance_zones"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/trendline/{symbol}",
        "Stock Detail Technical",
        "getTrendline",
        "trendline.analyze_trendline",
        "TrendlineResponse",
        required_fields=("symbol", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/volume/{symbol}",
        "Stock Detail Signals",
        "getVolumeAnalysisBySymbol",
        "volume_analysis.analyze_volume",
        "VolumeAnalysis",
        required_fields=("symbol", "status", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/risk-plans/{symbol}",
        "Stock Detail Risk",
        "getRiskPlanBySymbol",
        "risk.calculate_risk_plan",
        "RiskPlan",
        required_fields=("symbol", "current_price", "risk_level", "summary"),
        provider_domain="history",
        timeout_seconds=12,
    ),
    EndpointSpec(
        "GET",
        "/market/patterns/{symbol}",
        "Stock Detail Signals",
        "getMarketPatternsBySymbol",
        "pattern_detection.detect_patterns",
        "PatternResponse",
        required_fields=("patterns",),
        provider_domain="none",
    ),
    EndpointSpec(
        "GET",
        "/market/options/{symbol}",
        "Stock Detail Signals",
        "getOptionsIntelligenceBySymbol",
        "options_intelligence.analyze_symbol_options",
        "SymbolOptionsIntelligence",
        required_fields=("symbol", "status", "summary"),
        provider_domain="intelligence",
    ),
    EndpointSpec(
        "GET",
        "/market/liquidity/{symbol}",
        "Stock Detail Signals",
        "getLiquidityDashboardBySymbol",
        "liquidity_dashboard.analyze_symbol_liquidity",
        "SymbolLiquidityResponse",
        required_fields=("symbol", "status", "summary"),
        provider_domain="quotes+history",
    ),
    EndpointSpec(
        "GET",
        "/market/stock-analysis/{symbol}",
        "Stock Detail Aggregate",
        "getStockAnalysis",
        "stock_snapshots.service.get_stock_snapshot_service",
        "StockAnalysisAggregate",
        required_fields=("symbol", "partial", "snapshot_status"),
        optional_fields=("supportResistance", "trendline", "volumeAnalysis", "riskPlan", "relativeStrength", "stockRating", "multiTimeframeSignals", "patterns", "options", "liquidity", "leadershipSignal", "errors", "chartHistory"),
        provider_domain="quotes+history",
        partial_supported=True,
        timeout_seconds=5,
    ),
    EndpointSpec(
        "GET",
        "/analysis/stock/{symbol}",
        "Copilot Stock Context",
        "stock analysis context",
        "analysis.build_stock_analysis",
        "StockAnalysisResponse",
        required_fields=("symbol", "stock_rating", "relative_strength", "risk_plan"),
        provider_domain="history",
        timeout_seconds=15,
    ),
)


REPORT_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        "GET",
        "/report/daily",
        "Daily Report",
        "getDailyReport",
        "report.build_daily_report",
        "DailyReportResponse",
        required_fields=("report",),
        provider_domain="quotes+history",
        timeout_seconds=30,
        tier="optional",
    ),
    EndpointSpec(
        "GET",
        "/report/daily/pdf",
        "Daily Report PDF",
        "getDailyReportPdfUrl",
        "report.generate_daily_report_pdf",
        "application/pdf",
        required_fields=(),
        provider_domain="quotes+history",
        timeout_seconds=30,
        tier="optional",
    ),
)


COPILOT_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec(
        "GET",
        "/ai/market-summary",
        "AI Market Insight",
        "getMarketAISummary",
        "ai_summary.generate_market_narrative",
        "MarketAISummaryResponse",
        required_fields=("summary",),
        provider_domain="ai",
        timeout_seconds=30,
        tier="optional",
    ),
    EndpointSpec(
        "GET",
        "/ai/status",
        "AI Status",
        "getAIStatus",
        "openai_client.get_openai_status",
        "dict",
        required_fields=("enabled",),
        provider_domain="ai",
        tier="optional",
    ),
)


DEFAULT_SYMBOLS: tuple[str, ...] = (
    "SPY",
    "QQQ",
    "IWM",
    "AAPL",
    "MSFT",
    "NVDA",
    "AMD",
    "ARM",
    "SNDK",
    "MU",
    "TSLA",
)

SECONDARY_SYMBOLS: tuple[str, ...] = (
    "DIA",
    "XLK",
    "SOXX",
)


def get_endpoint_inventory(*, include_report: bool = False, include_copilot: bool = False) -> list[EndpointSpec]:
    specs = list(CORE_ENDPOINTS) + list(SYMBOL_ENDPOINTS)
    if include_report:
        specs.extend(REPORT_ENDPOINTS)
    if include_copilot:
        specs.extend(COPILOT_ENDPOINTS)
    return specs


def inventory_as_dicts(*, include_report: bool = False, include_copilot: bool = False) -> list[dict[str, object]]:
    return [spec.model_dump() for spec in get_endpoint_inventory(include_report=include_report, include_copilot=include_copilot)]
