import { StyleSheet, Text, View } from 'react-native';

import { Spacing, Theme } from '@/constants/theme';

type AIConfidenceBadgeProps = {
  confidence?: number | null;
  generatedBy?: string;
  nextUpdate?: string;
};

export function AIConfidenceBadge({
  confidence,
  generatedBy,
  nextUpdate,
}: AIConfidenceBadgeProps) {
  const hasConfidence = typeof confidence === 'number';

  return (
    <View style={styles.container}>
      <View style={styles.scoreBadge}>
        <Text style={styles.scoreLabel}>Confidence</Text>
        <Text style={styles.scoreValue}>{hasConfidence ? `${confidence}%` : 'N/A'}</Text>
      </View>

      <View style={styles.meta}>
        <Text style={styles.metaText}>Generated by {formatGenerator(generatedBy)}</Text>
        <Text style={styles.metaText}>{nextUpdate ?? 'Next update unavailable'}</Text>
      </View>
    </View>
  );
}

function formatGenerator(generatedBy?: string) {
  if (generatedBy?.toLowerCase() === 'openai') {
    return 'OpenAI';
  }

  return 'Rules-based';
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Spacing.two,
  },
  meta: {
    flex: 1,
    gap: Spacing.half,
  },
  metaText: {
    color: Theme.colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  scoreBadge: {
    alignItems: 'center',
    backgroundColor: Theme.colors.purpleSoft,
    borderColor: Theme.colors.purple,
    borderRadius: Theme.radii.small,
    borderWidth: 1,
    minWidth: 88,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  scoreLabel: {
    color: Theme.colors.textMuted,
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  scoreValue: {
    color: Theme.colors.purple,
    fontSize: 18,
    fontWeight: '900',
  },
});
