import { StyleSheet, Text, View } from 'react-native';

import { Spacing, Theme, Typography } from '@/constants/theme';
import { confidenceLabel, providerLabel } from '@/components/ui/ConfidenceFreshness';

export type ConfidenceIndicatorProps = {
  confidence?: number | null;
  generatedBy?: string;
  nextUpdate?: string;
};

export function ConfidenceIndicator({ confidence, generatedBy, nextUpdate }: ConfidenceIndicatorProps) {
  return (
    <View style={styles.container}>
      <View style={styles.scoreBadge}>
        <Text style={styles.scoreLabel}>Confidence</Text>
        <Text style={styles.scoreValue}>{confidenceLabel({ confidence, fallback: 'Confidence unavailable' }).replace(' confidence', '')}</Text>
      </View>
      <View style={styles.meta}>
        <Text style={styles.metaText}>Generated by {formatGenerator(generatedBy)}</Text>
        <Text style={styles.metaText}>{nextUpdate ?? 'Next update unavailable'}</Text>
      </View>
    </View>
  );
}

function formatGenerator(generatedBy?: string) {
  return generatedBy ? providerLabel(generatedBy) : 'Rules-based';
}

const styles = StyleSheet.create({
  container: { alignItems: 'center', flexDirection: 'row', gap: Spacing.two },
  meta: { flex: 1, gap: Spacing.half },
  metaText: { color: Theme.colors.textMuted, fontSize: Typography.caption.fontSize, fontWeight: Typography.weights.strong },
  scoreBadge: {
    alignItems: 'center',
    backgroundColor: Theme.colors.purpleSoft,
    borderColor: Theme.colors.purple,
    borderRadius: Theme.radii.small,
    borderWidth: 1,
    minWidth: 88,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  scoreLabel: { color: Theme.colors.textMuted, fontSize: Typography.chartAxis.fontSize, fontWeight: Typography.weights.strong, textTransform: 'uppercase' },
  scoreValue: { color: Theme.colors.purple, fontSize: Typography.sectionTitle.fontSize, fontWeight: Typography.weights.strong },
});
